runtime: nodejs18
instance_class: F2

env_variables:
  URL_FRONTEND: https://eduzone-frontend.netlify.app
  # Add other environment variables as needed

automatic_scaling:
  max_instances: 1

handlers:
  - url: /.*
    script: auto

network:
  session_affinity: true
